version: "2"

services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockfile
      target: dev
    command: npm run start:dev orders
    env_file:
      - './apps/orders/.env'
    depends_on:
      - mongodb-primary
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'  


volumes:
  mongodb_master_data:
    driver: local